#!/usr/bin/env bash

# Bash strict mode
set -o errtrace
set -o errexit
set -o nounset
set -o pipefail

IFS=$'\n\t'
LANG=C

declare -A dir
declare -A sha1

dir_data="${XDG_DATA_HOME:="${HOME}/.local/share"}"
dir_main="${DOOMWADDIR:="${dir_data}/games/doom"}"

dir["doom_2"]="${dir_main}/doom2.wad"
dir["doom_1"]="${dir_main}/doom1.wad"

dir["nrftl"]="${dir_main}/nrftl.wad"
dir["sigil_1"]="${dir_main}/sigil1.wad"
dir["sigil_2"]="${dir_main}/sigil2.wad"

sha1["iwad_doom_2"]="7ec7652fcfce8ddc6e801839291f0e28ef1d5ae7"
sha1["iwad_doom_1"]="9b07b02ab3c275a6a7570c3f73cc20d63a0e3833"

sha1["ewad_nrftl"]="3451288383fb16e196f273d9f85d58c1fda97bf4"
sha1["ewad_sigil_1"]="e2efdf379e1383c4e15c03de89063361897cd459"
sha1["ewad_sigil_2"]="ad2c6e8367afbeef74e9e09b6b1e4da88c0576b4"

check()
{
	if ! [[ -d "${dir_data}/Steam" ]]; then
		error "Steam directory does exit, have you installed it on the \$XDG_DATA_HOME?"
		exit 1
	else
		success "Steam directory found."
	fi

	if ! [[ -d "${dir_data}/Steam/steamapps/common/Ultimate Doom" ]]; then
		error "Could not find Ultimate Doom intallation."
		error "Check your Ultimate Doom installation on the Steam Client."
		error "Make sure to install in your \$XDG_DATA_HOME"
	else
		success "Ultimate Doom steam installation found."
	fi

	if ! [[ -d "${dir_data}/Steam/steamapps/common/Doom 2" ]]; then
		error "Could not find Doom 2 intallation."
		error "Check your Doom 2 installation on the Steam Client."
		error "Make sure to install in your \$XDG_DATA_HOME"
	else
		success "Doom 2 steam installation found."
	fi

	return 0
}

