#!/usr/bin/env bash

# Bash strict mode
set -o errtrace;
set -o errexit;
set -o nounset;
set -o pipefail;
IFS=$'\n\t'

dir_data="${XDG_DATA_HOME:="$HOME/.local/share"}";

dir_main="$dir_data/doom-utils";

dir_iwad="$dir_main/iwad";
dir_ewad="$dir_main/ewad";

iwad_doom_2="$dir_iwad/doom2.wad";
iwad_doom_1="$dir_iwad/doom1.wad";

ewad_nerve="$dir_ewad/nerve.wad";
ewad_sigil_1="$dir_ewad/sigil1.wad";
ewad_sigil_2="$dir_ewad/sigil2.wad";

iwad_doom_2_sha1="7ec7652fcfce8ddc6e801839291f0e28ef1d5ae7";
iwad_doom_1_sha1="9b07b02ab3c275a6a7570c3f73cc20d63a0e3833";

ewad_nerve_sha1="3451288383fb16e196f273d9f85d58c1fda97bf4";
ewad_sigil_2_sha1="ad2c6e8367afbeef74e9e09b6b1e4da88c0576b4";
ewad_sigil_1_sha1="e2efdf379e1383c4e15c03de89063361897cd459";

# Here be util commands
success() {
    echo "[ Success ] $1";
}

info() {
    echo "[ Info ] $1";
}

warn() {
    echo "[ Warn ] $1";
}

error() {
    echo "[ Error ] $1";
}

# Here be subcommands
help() {
    echo "Help";
    return 0;
}

find() {
    info "Checking Steam directory.";

    if ! [ -d "$dir_data/Steam" ];
        then
            error "Steam directory does exit, have you installed it on the $XDG_DATA_HOME?";
            exit 1;
        else
            success "Steam directory found.";
    fi


    info "Checking Doom installation.";

    if ! [ -d "$dir_data/Steam/steamapps/common/Ultimate Doom" ];
        then
            error "Could not find Ultimate Doom intallation.";
            error "Check your Ultimate Doom installation on the Steam Client.";
            error "Make sure to install in your \$XDG_DATA_HOME";
        else
            success "Ultimate Doom steam installation found.";
    fi;


    info "Checking Doom 2 installation."

    if ! [ -d "$dir_data/Steam/steamapps/common/Doom 2" ];
        then
            error "Could not find Doom 2 intallation.";
            error "Check your Doom 2 installation on the Steam Client.";
            error "Make sure to install in your \$XDG_DATA_HOME";
        else
            success "Doom 2 steam installation found.";
    fi;

    return 0;
}

list() {
    if ! [ -d "$dir_main" ]; then mkdir -p "$dir_main" ; fi;
    ls -l "$dir_main";
    return 0;
}

main() {
    if [ $# -eq 0 ]; then return 1; fi;

    case "$1" in
        (find)
            find "${@:2}";
            ;;
        (list)
            list "${@:2}";
            ;;
        (*)
            help "${@:2}";
            ;;
    esac;

    return 0;
}

main "$@";
