#!/usr/bin/env bash

# Bash strict mode
set -o errtrace
set -o errexit
set -o nounset
set -o pipefail

IFS=$'\n\t'
LANG=C

NAME="$(basename "$0")"
VERSION="${DOOM_UTILS_VERSION:-"dev"}"

DATA_DIR=${XDG_DATA_HOME:-"${HOME}/.local/share"}
DOOM_DIR="${DOOMWADDIR:-"${DATA_DIR}/games/doom"}"
PATHS=(
	"${DOOM_DIR}"
	/usr/local/share/games/doom
	/usr/local/share/doom
	/usr/share/games/doom
	/usr/share/doom
)
DOOM_PATH="$(echo "${PATHS[@]}" | tr ' ' ':')"

function __path()
{
	echo "export DOOMWADDIR=\"${DOOM_DIR}\""
	echo "export DOOMWADPATH=\"${DOOM_PATH}\""
	exit 0
}

function __help()
{
	echo "Usage: wadpath [OPTIONS]"
	echo "Options:"
	echo "    -h  Print this help message"
	echo "    -v  Print version information"
	echo ""
	exit 0

}

function __version()
{
	echo "${NAME} - DoomUtils ${VERSION}"
	exit 0
}

function __invalid()
{
	echo "Option -${OPTARG} is invalid" >&2
	exit 1
}

function __required_args()
{
	echo "Option -${OPTARG} requires an argument" >&2
	exit 1
}

function main()
{
	while getopts ":hv" option; do
		case "${option}" in
			h)
				__help
				;;
			v)
				__version
				;;
			\?)
				__invalid
				;;
			:)
				__required_args
				;;
		esac
	done
	__path
}

main "$@"

